[colors.normal]
black = '#1e2127'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#abb2bf'

[colors.bright]
black = '#5c6370'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#ffffff'

[colors.primary]
foreground = "#abb2bf"
background = "#282c34"

[colors.cursor]
text = "#282c34"
cursor = "#74ADE8"

[colors.selection]
text = "#abb2bf"
background = "#3A4A5E"
